#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyBlog.Common.Extensions;
    using MyBlog.Common.Helpers;
    using MyBlog.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ChangePassword.cshtml")]
    public partial class _Views_Account_ChangePassword_cshtml : System.Web.Mvc.WebViewPage<MyBlog.Web.Models.ChangePasswordViewModel>
    {
        public _Views_Account_ChangePassword_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Account\ChangePassword.cshtml"
  
    ViewBag.Title = "تغییر رمز عبور";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"col-lg-6 col-lg-offset-1 col-md-7 col-md-offset-0\"");

WriteLiteral(">\r\n    <h2>تغییر رمز عبور</h2>\r\n");

            
            #line 9 "..\..\Views\Account\ChangePassword.cshtml"
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Account\ChangePassword.cshtml"
     using (Html.BeginForm("ChangePassword", "Account", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Account\ChangePassword.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Account\ChangePassword.cshtml"
                                

            
            #line default
            #line hidden
WriteLiteral("        <hr />\r\n");

            
            #line 13 "..\..\Views\Account\ChangePassword.cshtml"
        
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Account\ChangePassword.cshtml"
   Write(Html.ValidationSummary("", new { @class = "text-danger" }));

            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Account\ChangePassword.cshtml"
                                                                   
        
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Account\ChangePassword.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Account\ChangePassword.cshtml"
                                

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"row control-group\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group col-xs-8 floating-label-form-group controls\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 17 "..\..\Views\Account\ChangePassword.cshtml"
           Write(Html.LabelFor(m => m.OldPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 18 "..\..\Views\Account\ChangePassword.cshtml"
           Write(Html.EditorFor(m => m.OldPassword, new { htmlAttributes = new { @class = "form-control left-text", placeholder = "رمز عبور فعلی" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 19 "..\..\Views\Account\ChangePassword.cshtml"
           Write(Html.ValidationMessageFor(m => m.OldPassword, null, new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row control-group\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group col-xs-8 floating-label-form-group controls\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 24 "..\..\Views\Account\ChangePassword.cshtml"
           Write(Html.LabelFor(m => m.NewPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 25 "..\..\Views\Account\ChangePassword.cshtml"
           Write(Html.EditorFor(m => m.NewPassword, new { htmlAttributes = new { @class = "form-control left-text", placeholder = "رمز عبور جدید" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 26 "..\..\Views\Account\ChangePassword.cshtml"
           Write(Html.ValidationMessageFor(m => m.NewPassword, null, new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row control-group\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group col-xs-8 floating-label-form-group controls\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 31 "..\..\Views\Account\ChangePassword.cshtml"
           Write(Html.LabelFor(m => m.ConfirmPassword));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 32 "..\..\Views\Account\ChangePassword.cshtml"
           Write(Html.EditorFor(m => m.ConfirmPassword, new { htmlAttributes = new { @class = "form-control left-text", placeholder = "تکرار رمز عبور جدید" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 33 "..\..\Views\Account\ChangePassword.cshtml"
           Write(Html.ValidationMessageFor(m => m.ConfirmPassword, null, new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <br>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group col-xs-8\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default pull-left\"");

WriteLiteral(">ارسال</button>\r\n            </div>\r\n        </div>\r\n");

            
            #line 42 "..\..\Views\Account\ChangePassword.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

        }
    }
}
#pragma warning restore 1591
