#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyBlog.Common.Extensions;
    using MyBlog.Common.Helpers;
    using MyBlog.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/ForgotPassword.cshtml")]
    public partial class _Views_Account_ForgotPassword_cshtml : System.Web.Mvc.WebViewPage<MyBlog.Web.Models.ForgotPasswordViewModel>
    {
        public _Views_Account_ForgotPassword_cshtml()
        {
        }
        public override void Execute()
        {
DefineSection("header", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 3 "..\..\Views\Account\ForgotPassword.cshtml"
Write(Html.GenerateMetaTag("", "", false, false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

            
            #line 6 "..\..\Views\Account\ForgotPassword.cshtml"
  
    ViewBag.Title = "بازآوری رمز عبور";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"col-lg-6 col-lg-offset-1 col-md-7 col-md-offset-0\"");

WriteLiteral(">\r\n    <h2>بازآوری رمز عبور</h2>\r\n    <p>ایمیل خود را وارد نمایید</p>\r\n");

            
            #line 13 "..\..\Views\Account\ForgotPassword.cshtml"
    
            
            #line default
            #line hidden
            
            #line 13 "..\..\Views\Account\ForgotPassword.cshtml"
     using (Html.BeginForm("ForgotPassword", "Account", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
    {
        
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Account\ForgotPassword.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Account\ForgotPassword.cshtml"
                                

            
            #line default
            #line hidden
WriteLiteral("        <hr />\r\n");

            
            #line 17 "..\..\Views\Account\ForgotPassword.cshtml"
        
            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Account\ForgotPassword.cshtml"
   Write(Html.ValidationSummary("", new { @class = "text-danger" }));

            
            #line default
            #line hidden
            
            #line 17 "..\..\Views\Account\ForgotPassword.cshtml"
                                                                   
        
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Account\ForgotPassword.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Account\ForgotPassword.cshtml"
                                

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"row control-group\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group col-xs-8 floating-label-form-group controls\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 21 "..\..\Views\Account\ForgotPassword.cshtml"
           Write(Html.LabelFor(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 22 "..\..\Views\Account\ForgotPassword.cshtml"
           Write(Html.EditorFor(m => m.Email, new { htmlAttributes = new { @class = "form-control left-text", placeholder = "ایمیل" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 23 "..\..\Views\Account\ForgotPassword.cshtml"
           Write(Html.ValidationMessageFor(m => m.Email, null, new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <br>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group col-xs-8\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default pull-left\"");

WriteLiteral(">ارسال</button>\r\n            </div>\r\n        </div>\r\n");

            
            #line 32 "..\..\Views\Account\ForgotPassword.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 36 "..\..\Views\Account\ForgotPassword.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
