#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyBlog.Common.Extensions;
    using MyBlog.Common.Helpers;
    using MyBlog.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/VerifyCode.cshtml")]
    public partial class _Views_Account_VerifyCode_cshtml : System.Web.Mvc.WebViewPage<MyBlog.Web.Models.VerifyCodeViewModel>
    {
        public _Views_Account_VerifyCode_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Account\VerifyCode.cshtml"
  
    ViewBag.Title = "Verify";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 6 "..\..\Views\Account\VerifyCode.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h2>\r\n\r\n");

            
            #line 8 "..\..\Views\Account\VerifyCode.cshtml"
 using (Html.BeginForm("VerifyCode", "Account", new { ReturnUrl = Model.ReturnUrl }, FormMethod.Post, new { @class = "form-horizontal", role = "form" })) {
    
            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Account\VerifyCode.cshtml"
Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 9 "..\..\Views\Account\VerifyCode.cshtml"
                            
    
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Account\VerifyCode.cshtml"
Write(Html.Hidden("provider", @Model.Provider));

            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Account\VerifyCode.cshtml"
                                             
    
            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Account\VerifyCode.cshtml"
Write(Html.Hidden("rememberMe", @Model.RememberMe));

            
            #line default
            #line hidden
            
            #line 11 "..\..\Views\Account\VerifyCode.cshtml"
                                                 

            
            #line default
            #line hidden
WriteLiteral("    <h4>Enter verification code</h4>\r\n");

WriteLiteral("    <hr />\r\n");

            
            #line 14 "..\..\Views\Account\VerifyCode.cshtml"
    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Account\VerifyCode.cshtml"
Write(Html.ValidationSummary("", new { @class = "text-danger" }));

            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Account\VerifyCode.cshtml"
                                                               

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 16 "..\..\Views\Account\VerifyCode.cshtml"
   Write(Html.LabelFor(m => m.Code, new { @class = "col-md-2 control-label" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 18 "..\..\Views\Account\VerifyCode.cshtml"
       Write(Html.TextBoxFor(m => m.Code, new { @class = "form-control" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 24 "..\..\Views\Account\VerifyCode.cshtml"
           Write(Html.CheckBoxFor(m => m.RememberBrowser));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 25 "..\..\Views\Account\VerifyCode.cshtml"
           Write(Html.LabelFor(m => m.RememberBrowser));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n    </div>\r\n");

WriteLiteral("    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

WriteLiteral(">\r\n            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" value=\"Submit\"");

WriteLiteral(" />\r\n        </div>\r\n    </div>\r\n");

            
            #line 34 "..\..\Views\Account\VerifyCode.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("Scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 37 "..\..\Views\Account\VerifyCode.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
