#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyBlog.Common.Extensions;
    using MyBlog.Common.Helpers;
    using MyBlog.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Tag/Index.cshtml")]
    public partial class _Areas_Admin_Views_Tag_Index_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<MyBlog.Domain.TagEntity>>
    {
        public _Areas_Admin_Views_Tag_Index_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Tag\Index.cshtml"
  
    ViewBag.Title = "لیست تگ ها";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("ContentHeader", () => {

WriteLiteral("\r\n    <h2>لیست تگ ها</h2>\r\n");

});

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"box\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"box-header\"");

WriteLiteral(">\r\n            <p");

WriteLiteral(" class=\"box-title\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 16 "..\..\Areas\Admin\Views\Tag\Index.cshtml"
           Write(Html.ActionLink("ایجاد تگ جدید", "Create"));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </p>\r\n        </div>\r\n        <table");

WriteLiteral(" class=\"table table-bordered\"");

WriteLiteral(">\r\n            <thead>\r\n                <tr>\r\n                    <th>\r\n");

WriteLiteral("                        ");

            
            #line 23 "..\..\Areas\Admin\Views\Tag\Index.cshtml"
                   Write(Html.DisplayNameFor(model => model.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </th>\r\n                    <th>\r\n");

WriteLiteral("                        ");

            
            #line 26 "..\..\Areas\Admin\Views\Tag\Index.cshtml"
                   Write(Html.DisplayNameFor(model => model.Slug));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </th>\r\n                    <th></th>\r\n                </tr>" +
"\r\n            </thead>\r\n            <tbody>\r\n");

            
            #line 32 "..\..\Areas\Admin\Views\Tag\Index.cshtml"
                
            
            #line default
            #line hidden
            
            #line 32 "..\..\Areas\Admin\Views\Tag\Index.cshtml"
                 foreach (var item in Model)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td>\r\n");

WriteLiteral("                            ");

            
            #line 36 "..\..\Areas\Admin\Views\Tag\Index.cshtml"
                       Write(Html.DisplayFor(modelItem => item.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n");

WriteLiteral("                            ");

            
            #line 39 "..\..\Areas\Admin\Views\Tag\Index.cshtml"
                       Write(Html.DisplayFor(modelItem => item.Slug));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </td>\r\n                        <td>\r\n");

WriteLiteral("                            ");

            
            #line 42 "..\..\Areas\Admin\Views\Tag\Index.cshtml"
                       Write(Html.ActionLink("ویرایش", "Edit", new { id = item.Id }));

            
            #line default
            #line hidden
WriteLiteral(" |\r\n                            <a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" data-id=\"");

            
            #line 43 "..\..\Areas\Admin\Views\Tag\Index.cshtml"
                                            Write(item.Id);

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(" class=\"delete-item\"");

WriteLiteral(">حذف</a>\r\n                        </td>\r\n                    </tr>\r\n");

            
            #line 46 "..\..\Areas\Admin\Views\Tag\Index.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </tbody>\r\n        </table>\r\n    </div>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script>\r\n        helper.deleteFromTable(\'");

            
            #line 53 "..\..\Areas\Admin\Views\Tag\Index.cshtml"
                           Write(Url.Action("Delete"));

            
            #line default
            #line hidden
WriteLiteral("\', \'.delete-item\');\r\n    </script>\r\n");

});

        }
    }
}
#pragma warning restore 1591
