#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyBlog.Common.Extensions;
    using MyBlog.Common.Helpers;
    using MyBlog.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Tag/Create.cshtml")]
    public partial class _Areas_Admin_Views_Tag_Create_cshtml : System.Web.Mvc.WebViewPage<MyBlog.Domain.TagEntity>
    {
        public _Areas_Admin_Views_Tag_Create_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Tag\Create.cshtml"
  
    ViewBag.Title = "ایجاد تگ جدید";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("ContentHeader", () => {

WriteLiteral("\r\n    <h2>ایجاد تگ</h2>\r\n");

});

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 12 "..\..\Areas\Admin\Views\Tag\Create.cshtml"
Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"box box-primary\"");

WriteLiteral(">\r\n");

            
            #line 15 "..\..\Areas\Admin\Views\Tag\Create.cshtml"
        
            
            #line default
            #line hidden
            
            #line 15 "..\..\Areas\Admin\Views\Tag\Create.cshtml"
         using (Html.BeginForm("Create", "Tag", FormMethod.Post))
        {
            
            
            #line default
            #line hidden
            
            #line 17 "..\..\Areas\Admin\Views\Tag\Create.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 17 "..\..\Areas\Admin\Views\Tag\Create.cshtml"
                                    


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"form-horizontal box-body\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 21 "..\..\Areas\Admin\Views\Tag\Create.cshtml"
               Write(Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-4\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 23 "..\..\Areas\Admin\Views\Tag\Create.cshtml"
                   Write(Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control type-direction" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 24 "..\..\Areas\Admin\Views\Tag\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n            </div>\r\n");

            
            #line 28 "..\..\Areas\Admin\Views\Tag\Create.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"box-footer\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"ایجاد\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" />\r\n            </div>\r\n");

            
            #line 32 "..\..\Areas\Admin\Views\Tag\Create.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n\r\n    <div>\r\n");

WriteLiteral("        ");

            
            #line 36 "..\..\Areas\Admin\Views\Tag\Create.cshtml"
   Write(Html.ActionLink("بازگشت به لیست", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
