#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyBlog.Common.Extensions;
    using MyBlog.Common.Helpers;
    using MyBlog.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/About.cshtml")]
    public partial class _Views_Home_About_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Home_About_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Views\Home\About.cshtml"
  
    ViewBag.Title = "درباره";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("header", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 6 "..\..\Views\Home\About.cshtml"
Write(Html.GenerateMetaTag(
        "محسن اسماعیل پور, Mohsen Esmailpour, بلاگ من, .net, c#, asp.net mvc, entity framework, javascript, jquery, web api",
                "I'm newbie software developer with a particular interest in web technologies and creating web application with Microsoft technologies.",
        true, true, "محسن اسماعیل پور (http://www.mohsen.es)"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 10 "..\..\Views\Home\About.cshtml"
Write(Styles.Render("//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1\"");

WriteLiteral(" style=\"text-align: center\"");

WriteLiteral(">\r\n    <p>هر چی فکر کردم چیزی به ذهنم نرسید که بنویسیم. شاید در آینده بیشتر فکر ک" +
"ردم !</p>\r\n    ");

WriteLiteral("\r\n    <div");

WriteLiteral(" class=\"social\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"menu-item\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" id=\"active\"");

WriteLiteral(" class=\"icon fa fa-twitter\"");

WriteLiteral(" style=\"display: block;\"");

WriteLiteral("></span>\r\n            <a");

WriteLiteral(" id=\"hover\"");

WriteLiteral(" class=\"text\"");

WriteLiteral(" href=\"https://twitter.com/moesmp\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-twitter\"");

WriteLiteral("></i>\r\n            </a>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"menu-item\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" id=\"active\"");

WriteLiteral(" class=\"icon fa fa-linkedin\"");

WriteLiteral(" style=\"display: block;\"");

WriteLiteral("></span>\r\n            <a");

WriteLiteral(" id=\"hover\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"text\"");

WriteLiteral(" href=\"http://ir.linkedin.com/pub/mohsen-esmailpour/51/38b/827\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-linkedin\"");

WriteLiteral("></i>\r\n            </a>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"menu-item\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" id=\"active\"");

WriteLiteral(" class=\"icon fa fa-google-plus\"");

WriteLiteral(" style=\"display: block;\"");

WriteLiteral("></span>\r\n            <a");

WriteLiteral(" id=\"hover\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"text\"");

WriteLiteral(" href=\"https://plus.google.com/u/0/+MohsenEsmailpour\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-google-plus\"");

WriteLiteral("></i>\r\n            </a>\r\n        </div>\r\n        <div");

WriteLiteral(" class=\"menu-item\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" id=\"active\"");

WriteLiteral(" class=\"icon fa fa-stack-overflow\"");

WriteLiteral(" style=\"display: block;\"");

WriteLiteral("></span>\r\n            <a");

WriteLiteral(" id=\"hover\"");

WriteLiteral(" target=\"_blank\"");

WriteLiteral(" class=\"text\"");

WriteLiteral(" href=\"http://stackoverflow.com/users/1385614/mo-esmp\"");

WriteLiteral(">\r\n                <i");

WriteLiteral(" class=\"fa fa-stack-overflow\"");

WriteLiteral("></i>\r\n            </a>\r\n        </div>\r\n    </div>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral(@"
    <script>
        $(function () {
            $('.menu-item').hover(function () {
                $('#active', this).toggleClass('active');
                $('#active', this).css({ 'display': 'block' }); //adds context
            });
        });
    </script>
");

});

        }
    }
}
#pragma warning restore 1591
