#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System.Web.Mvc;
    using System.Web.Mvc.Html;

#line 1 "..\..\Views\Account\_ChangePasswordPartial.cshtml"

#line default
#line hidden

    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Account/_ChangePasswordPartial.cshtml")]
    public partial class _Views_Account__ChangePasswordPartial_cshtml : System.Web.Mvc.WebViewPage<MyBlog.Web.Models.ChangePasswordViewModel>
    {
        public _Views_Account__ChangePasswordPartial_cshtml()
        {
        }

        public override void Execute()
        {
#line 4 "..\..\Views\Account\_ChangePasswordPartial.cshtml"
            using (Html.BeginForm("Manage", "Account", FormMethod.Post, new { @class = "form-horizontal", role = "form" }))
            {
#line default
#line hidden

#line 6 "..\..\Views\Account\_ChangePasswordPartial.cshtml"
                Write(Html.AntiForgeryToken());

#line default
#line hidden

#line 6 "..\..\Views\Account\_ChangePasswordPartial.cshtml"

#line default
#line hidden
                WriteLiteral("    <h4>Change Password Form</h4>\r\n");

                WriteLiteral("    <hr />\r\n");

#line 9 "..\..\Views\Account\_ChangePasswordPartial.cshtml"

#line default
#line hidden

#line 9 "..\..\Views\Account\_ChangePasswordPartial.cshtml"
                Write(Html.ValidationSummary("", new { @class = "text-danger" }));

#line default
#line hidden

#line 9 "..\..\Views\Account\_ChangePasswordPartial.cshtml"

#line default
#line hidden
                WriteLiteral("    <div");

                WriteLiteral(" class=\"form-group\"");

                WriteLiteral(">\r\n");

                WriteLiteral("        ");

#line 11 "..\..\Views\Account\_ChangePasswordPartial.cshtml"
                Write(Html.LabelFor(m => m.OldPassword, new { @class = "col-md-2 control-label" }));

#line default
#line hidden
                WriteLiteral("\r\n        <div");

                WriteLiteral(" class=\"col-md-10\"");

                WriteLiteral(">\r\n");

                WriteLiteral("            ");

#line 13 "..\..\Views\Account\_ChangePasswordPartial.cshtml"
                Write(Html.PasswordFor(m => m.OldPassword, new { @class = "form-control" }));

#line default
#line hidden
                WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

                WriteLiteral("    <div");

                WriteLiteral(" class=\"form-group\"");

                WriteLiteral(">\r\n");

                WriteLiteral("        ");

#line 17 "..\..\Views\Account\_ChangePasswordPartial.cshtml"
                Write(Html.LabelFor(m => m.NewPassword, new { @class = "col-md-2 control-label" }));

#line default
#line hidden
                WriteLiteral("\r\n        <div");

                WriteLiteral(" class=\"col-md-10\"");

                WriteLiteral(">\r\n");

                WriteLiteral("            ");

#line 19 "..\..\Views\Account\_ChangePasswordPartial.cshtml"
                Write(Html.PasswordFor(m => m.NewPassword, new { @class = "form-control" }));

#line default
#line hidden
                WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

                WriteLiteral("    <div");

                WriteLiteral(" class=\"form-group\"");

                WriteLiteral(">\r\n");

                WriteLiteral("        ");

#line 23 "..\..\Views\Account\_ChangePasswordPartial.cshtml"
                Write(Html.LabelFor(m => m.ConfirmPassword, new { @class = "col-md-2 control-label" }));

#line default
#line hidden
                WriteLiteral("\r\n        <div");

                WriteLiteral(" class=\"col-md-10\"");

                WriteLiteral(">\r\n");

                WriteLiteral("            ");

#line 25 "..\..\Views\Account\_ChangePasswordPartial.cshtml"
                Write(Html.PasswordFor(m => m.ConfirmPassword, new { @class = "form-control" }));

#line default
#line hidden
                WriteLiteral("\r\n        </div>\r\n    </div>\r\n");

#line 28 "..\..\Views\Account\_ChangePasswordPartial.cshtml"

#line default
#line hidden
                WriteLiteral("    <div");

                WriteLiteral(" class=\"form-group\"");

                WriteLiteral(">\r\n        <div");

                WriteLiteral(" class=\"col-md-offset-2 col-md-10\"");

                WriteLiteral(">\r\n            <input");

                WriteLiteral(" type=\"submit\"");

                WriteLiteral(" value=\"Change password\"");

                WriteLiteral(" class=\"btn btn-default\"");

                WriteLiteral(" />\r\n        </div>\r\n    </div>\r\n");

#line 34 "..\..\Views\Account\_ChangePasswordPartial.cshtml"
            }

#line default
#line hidden
        }
    }
}

#pragma warning restore 1591