#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyBlog.Common.Extensions;
    using MyBlog.Common.Helpers;
    using MyBlog.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Home/Contact.cshtml")]
    public partial class _Views_Home_Contact_cshtml : System.Web.Mvc.WebViewPage<MyBlog.Domain.ContactMessageEntity>
    {
        public _Views_Home_Contact_cshtml()
        {
        }
        public override void Execute()
        {
DefineSection("header", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 4 "..\..\Views\Home\Contact.cshtml"
Write(Html.GenerateMetaTag(
        "محسن اسماعیل پور, Mohsen Esmailpour, بلاگ من, .net, c#, asp.net mvc, entity framework, javascript, jquery, web api",
                "I'm newbie software developer with a particular interest in web technologies and creating web application with Microsoft technologies.",
        true, true, "محسن اسماعیل پور (http://www.mohsen.es)"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Views\Home\Contact.cshtml"
Write(Styles.Render("//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 9 "..\..\Views\Home\Contact.cshtml"
Write(Styles.Render("//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

            
            #line 12 "..\..\Views\Home\Contact.cshtml"
  
    ViewBag.Title = "تماس";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" class=\"col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1\"");

WriteLiteral(">\r\n\r\n    <p><i");

WriteLiteral(" class=\"fa fa-envelope-o\"");

WriteLiteral("></i> info [at] mohsen [dot] es</p>\r\n    <p><i");

WriteLiteral(" class=\"fa fa-send-o\"");

WriteLiteral("></i> برای ارتباط با من میتوانید از فرم زیر استفاده نمایید.</p>\r\n\r\n");

            
            #line 21 "..\..\Views\Home\Contact.cshtml"
    
            
            #line default
            #line hidden
            
            #line 21 "..\..\Views\Home\Contact.cshtml"
     if (!ViewData.ModelState.IsValid)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"alert alert-danger\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"alert\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">×</button>\r\n");

WriteLiteral("            ");

            
            #line 25 "..\..\Views\Home\Contact.cshtml"
       Write(Html.ValidationSummary());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n");

            
            #line 27 "..\..\Views\Home\Contact.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 29 "..\..\Views\Home\Contact.cshtml"
    
            
            #line default
            #line hidden
            
            #line 29 "..\..\Views\Home\Contact.cshtml"
     if (TempData["Successful"] != null)
    {

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"alert alert-success\"");

WriteLiteral(">\r\n            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"alert\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">×</button>\r\n            <strong>با تشکر پیام شما با موفقیت ثبت شد.</strong>\r\n   " +
"     </div>\r\n");

            
            #line 35 "..\..\Views\Home\Contact.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 37 "..\..\Views\Home\Contact.cshtml"
    
            
            #line default
            #line hidden
            
            #line 37 "..\..\Views\Home\Contact.cshtml"
     using (Html.BeginForm("Contact", "Home", FormMethod.Post, new { role = "form" }))
    {
        
            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Home\Contact.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 39 "..\..\Views\Home\Contact.cshtml"
                                

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" class=\"row control-group\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group col-xs-8 floating-label-form-group controls\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 42 "..\..\Views\Home\Contact.cshtml"
           Write(Html.LabelFor(m => m.Name));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 43 "..\..\Views\Home\Contact.cshtml"
           Write(Html.EditorFor(m => m.Name, new { htmlAttributes = new { @class = "form-control type-direction", placeholder = "نام" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 44 "..\..\Views\Home\Contact.cshtml"
           Write(Html.ValidationMessageFor(m => m.Name, null, new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row control-group\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group col-xs-8 floating-label-form-group controls\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 49 "..\..\Views\Home\Contact.cshtml"
           Write(Html.LabelFor(m => m.Email));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 50 "..\..\Views\Home\Contact.cshtml"
           Write(Html.EditorFor(m => m.Email, new { htmlAttributes = new { @class = "form-control left-text", placeholder = "ایمیل" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 51 "..\..\Views\Home\Contact.cshtml"
           Write(Html.ValidationMessageFor(m => m.Email, null, new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row control-group\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group col-xs-12 floating-label-form-group controls\"");

WriteLiteral(">\r\n");

WriteLiteral("                ");

            
            #line 56 "..\..\Views\Home\Contact.cshtml"
           Write(Html.LabelFor(m => m.Message));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 57 "..\..\Views\Home\Contact.cshtml"
           Write(Html.EditorFor(m => m.Message, new { htmlAttributes = new { @class = "form-control type-direction auto-size", placeholder = "پیام" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                ");

            
            #line 58 "..\..\Views\Home\Contact.cshtml"
           Write(Html.ValidationMessageFor(m => m.Message, null, new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n        </div>\r\n");

WriteLiteral("        <br>\r\n");

WriteLiteral("        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"form-group col-xs-12\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default pull-left\"");

WriteLiteral(">ارسال</button>\r\n            </div>\r\n        </div>\r\n");

            
            #line 67 "..\..\Views\Home\Contact.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 71 "..\..\Views\Home\Contact.cshtml"
Write(Scripts.Render("~/bundles/jqueryval"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 72 "..\..\Views\Home\Contact.cshtml"
Write(Scripts.Render("~/Scripts/jquery.autosize.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
