#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyBlog.Common.Extensions;
    using MyBlog.Common.Helpers;
    using MyBlog.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Admin/Views/Post/Create.cshtml")]
    public partial class _Areas_Admin_Views_Post_Create_cshtml : System.Web.Mvc.WebViewPage<MyBlog.Web.Areas.Admin.Models.PostViewModel>
    {
        public _Areas_Admin_Views_Post_Create_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Areas\Admin\Views\Post\Create.cshtml"
  
    ViewBag.Title = "ایجاد مقاله جدید";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

DefineSection("header", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Areas\Admin\Views\Post\Create.cshtml"
Write(Styles.Render("~/Content/admin/bootstrap-tagsinput.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

DefineSection("ContentHeader", () => {

WriteLiteral("\r\n    <h2>ایجاد مقاله</h2>\r\n");

});

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 16 "..\..\Areas\Admin\Views\Post\Create.cshtml"
Write(Html.ValidationSummary(true, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n    <div");

WriteLiteral(" class=\"box box-primary\"");

WriteLiteral(">\r\n");

            
            #line 19 "..\..\Areas\Admin\Views\Post\Create.cshtml"
        
            
            #line default
            #line hidden
            
            #line 19 "..\..\Areas\Admin\Views\Post\Create.cshtml"
         using (Html.BeginForm("Create", "Post", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            
            
            #line default
            #line hidden
            
            #line 21 "..\..\Areas\Admin\Views\Post\Create.cshtml"
       Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 21 "..\..\Areas\Admin\Views\Post\Create.cshtml"
                                    


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"form-horizontal box-body\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 25 "..\..\Areas\Admin\Views\Post\Create.cshtml"
               Write(Html.LabelFor(model => model.Post.Title, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 27 "..\..\Areas\Admin\Views\Post\Create.cshtml"
                   Write(Html.EditorFor(model => model.Post.Title, new { htmlAttributes = new { @class = "form-control type-direction" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 28 "..\..\Areas\Admin\Views\Post\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.Post.Title, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 33 "..\..\Areas\Admin\Views\Post\Create.cshtml"
               Write(Html.LabelFor(model => model.Post.Content, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 35 "..\..\Areas\Admin\Views\Post\Create.cshtml"
                   Write(Html.EditorFor(model => model.Post.Content, new { htmlAttributes = new { @class = "form-control" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 36 "..\..\Areas\Admin\Views\Post\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.Post.Content, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 41 "..\..\Areas\Admin\Views\Post\Create.cshtml"
               Write(Html.LabelFor(model => model.Post.Tags, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 43 "..\..\Areas\Admin\Views\Post\Create.cshtml"
                   Write(Html.EditorFor(model => model.Tags, new { htmlAttributes = new { @class = "form-control left-text" } }));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                        ");

            
            #line 44 "..\..\Areas\Admin\Views\Post\Create.cshtml"
                   Write(Html.ValidationMessageFor(model => model.Tags, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n                </div>\r\n\r\n                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n");

WriteLiteral("                    ");

            
            #line 49 "..\..\Areas\Admin\Views\Post\Create.cshtml"
               Write(Html.LabelFor(model => model.Post.IsEnabled, htmlAttributes: new { @class = "control-label col-md-2" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <div");

WriteLiteral(" class=\"col-md-10\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"checkbox\"");

WriteLiteral(">\r\n                            <label>\r\n");

WriteLiteral("                                ");

            
            #line 53 "..\..\Areas\Admin\Views\Post\Create.cshtml"
                           Write(Html.EditorFor(model => model.Post.IsEnabled));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </label>\r\n");

WriteLiteral("                            ");

            
            #line 55 "..\..\Areas\Admin\Views\Post\Create.cshtml"
                       Write(Html.ValidationMessageFor(model => model.Post.IsEnabled, "", new { @class = "text-danger" }));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n                    </div>\r\n                </d" +
"iv>\r\n            </div>\r\n");

            
            #line 60 "..\..\Areas\Admin\Views\Post\Create.cshtml"


            
            #line default
            #line hidden
WriteLiteral("            <div");

WriteLiteral(" class=\"box-footer\"");

WriteLiteral(">\r\n                <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" value=\"ایجاد\"");

WriteLiteral(" class=\"btn btn-primary\"");

WriteLiteral(" />\r\n            </div>\r\n");

            
            #line 64 "..\..\Areas\Admin\Views\Post\Create.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n\r\n    <div>\r\n");

WriteLiteral("        ");

            
            #line 68 "..\..\Areas\Admin\Views\Post\Create.cshtml"
   Write(Html.ActionLink("بازگشت به لیست", "Index"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 73 "..\..\Areas\Admin\Views\Post\Create.cshtml"
Write(Scripts.Render("~/Areas/Admin/Scripts/ckeditor/ckeditor.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 74 "..\..\Areas\Admin\Views\Post\Create.cshtml"
Write(Scripts.Render("~/bundles/tagsinput"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 75 "..\..\Areas\Admin\Views\Post\Create.cshtml"
Write(Scripts.Render("~/Areas/Admin/Scripts/pages/post.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
