#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyBlog.Common.Extensions;
    using MyBlog.Common.Helpers;
    using MyBlog.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Layout.cshtml")]
    public partial class _Views_Shared__Layout_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Shared__Layout_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!DOCTYPE html>\r\n<html");

WriteLiteral(" lang=\"fa\"");

WriteLiteral(">\r\n<head>\r\n    <meta");

WriteLiteral(" charset=\"utf-8\"");

WriteLiteral(" />\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Type\"");

WriteLiteral(" content=\"text/html; charset=utf-8\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"viewport\"");

WriteLiteral(" content=\"width=device-width, initial-scale=1.0\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" http-equiv=\"Content-Language\"");

WriteLiteral(" content=\"fa\"");

WriteLiteral(">\r\n    <meta");

WriteLiteral(" name=\"apple-mobile-web-app-capable\"");

WriteLiteral(" content=\"yes\"");

WriteLiteral(">\r\n    <title>");

            
            #line 9 "..\..\Views\Shared\_Layout.cshtml"
      Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(" - بلاگ من</title>\r\n    <link");

WriteLiteral(" rel=\"shortcut icon\"");

WriteAttribute("href", Tuple.Create(" href=\"", 413), Tuple.Create("\"", 433)
, Tuple.Create(Tuple.Create("", 420), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 420), false)
);

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(">\r\n    <link");

WriteLiteral(" rel=\"icon\"");

WriteAttribute("href", Tuple.Create(" href=\"", 477), Tuple.Create("\"", 497)
, Tuple.Create(Tuple.Create("", 484), Tuple.Create<System.Object, System.Int32>(Href("~/favicon.ico")
, 484), false)
);

WriteLiteral(" type=\"image/x-icon\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 12 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("header", false));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 13 "..\..\Views\Shared\_Layout.cshtml"
Write(Styles.Render("~/content/css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

            
            #line 14 "..\..\Views\Shared\_Layout.cshtml"
    
            
            #line default
            #line hidden
            
            #line 14 "..\..\Views\Shared\_Layout.cshtml"
     if (!string.IsNullOrWhiteSpace(Session["OsSpecificCss"].ToString()))
    { 
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Shared\_Layout.cshtml"
 Write(Styles.Render(Session["OsSpecificCss"].ToString()));

            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Shared\_Layout.cshtml"
                                                          }

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteLiteral(" data-pace-options=\'{ \"ajax\": false }\'");

WriteAttribute("src", Tuple.Create(" src=\"", 780), Tuple.Create("\"", 807)
, Tuple.Create(Tuple.Create("", 786), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/pace.min.js")
, 786), false)
);

WriteLiteral(@" async defer></script>
    <!--[if lt IE 9]>
        <script src=""https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js""></script>
        <script src=""https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js""></script>
    <![endif]-->
</head>
<body");

WriteLiteral(" dir=\"rtl\"");

WriteLiteral(">\r\n    <!-- Navigation -->\r\n    <nav");

WriteLiteral(" class=\"navbar navbar-default navbar-custom navbar-fixed-top\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container-fluid\"");

WriteLiteral(">\r\n            <!-- Brand and toggle get grouped for better mobile display -->\r\n " +
"           <div");

WriteLiteral(" class=\"navbar-header page-scroll\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"navbar-toggle\"");

WriteLiteral(" data-toggle=\"collapse\"");

WriteLiteral(" data-target=\"#bs-example-navbar-collapse-1\"");

WriteLiteral(">\r\n                    <span");

WriteLiteral(" class=\"sr-only\"");

WriteLiteral(">Toggle navigation</span>\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                    <span");

WriteLiteral(" class=\"icon-bar\"");

WriteLiteral("></span>\r\n                </button>\r\n                <a");

WriteLiteral(" class=\"navbar-brand\"");

WriteLiteral(" href=\"/\"");

WriteLiteral(">بلاگ من</a>\r\n            </div>\r\n            <!-- Collect the nav links, forms, " +
"and other content for toggling -->\r\n            <div");

WriteLiteral(" class=\"collapse navbar-collapse\"");

WriteLiteral(" id=\"bs-example-navbar-collapse-1\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"nav navbar-nav navbar-right\"");

WriteLiteral(">\r\n                    <li> <a");

WriteLiteral(" href=\"/\"");

WriteLiteral(">صفحه اصلی</a> </li>\r\n                    <li> <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2123), Tuple.Create("\"", 2158)
            
            #line 40 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2130), Tuple.Create<System.Object, System.Int32>(Url.Action("About", "Home")
            
            #line default
            #line hidden
, 2130), false)
);

WriteLiteral(">درباره</a> </li>\r\n                    <li> <a");

WriteAttribute("href", Tuple.Create(" href=\"", 2205), Tuple.Create("\"", 2242)
            
            #line 41 "..\..\Views\Shared\_Layout.cshtml"
, Tuple.Create(Tuple.Create("", 2212), Tuple.Create<System.Object, System.Int32>(Url.Action("Contact", "Home")
            
            #line default
            #line hidden
, 2212), false)
);

WriteLiteral(">تماس</a> </li>\r\n                </ul>\r\n            </div>\r\n            <!-- /.na" +
"vbar-collapse -->\r\n        </div>\r\n        <!-- /.container -->\r\n    </nav>\r\n\r\n " +
"   <!-- Set your background image for this header on the line below. -->\r\n    <h" +
"eader");

WriteLiteral(" class=\"intro-header\"");

WriteLiteral(" style=\"background-color: black\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"site-heading\"");

WriteLiteral(">\r\n                        <h1>{ code }</h1>\r\n                        <hr");

WriteLiteral(" class=\"x-small\"");

WriteLiteral(">\r\n                        <span");

WriteLiteral(" class=\"subheading\"");

WriteLiteral(">for fun</span>\r\n                    </div>\r\n                </div>\r\n            " +
"</div>\r\n        </div>\r\n    </header>\r\n\r\n    <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n");

WriteLiteral("            ");

            
            #line 66 "..\..\Views\Shared\_Layout.cshtml"
       Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n\r\n    <!-- Footer -->\r\n    <footer>\r\n        <hr />" +
"\r\n        <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1\"");

WriteLiteral(">\r\n                    <p");

WriteLiteral(" class=\"copyright text-muted\"");

WriteLiteral(">&copy; ");

            
            #line 76 "..\..\Views\Shared\_Layout.cshtml"
                                                      Write(DateTime.Now.GetJalaliYear().ToString().ToPersianDigits());

            
            #line default
            #line hidden
WriteLiteral(" Mohsen.es </p>\r\n                </div>\r\n            </div>\r\n        </div>\r\n    " +
"</footer>\r\n\r\n");

WriteLiteral("    ");

            
            #line 82 "..\..\Views\Shared\_Layout.cshtml"
Write(Scripts.Render("~/bundles/jquery"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3571), Tuple.Create("\"", 3603)
, Tuple.Create(Tuple.Create("", 3577), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/bootstrap-rtl.js")
, 3577), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3627), Tuple.Create("\"", 3653)
, Tuple.Create(Tuple.Create("", 3633), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/respond.js")
, 3633), false)
);

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 3677), Tuple.Create("\"", 3703)
, Tuple.Create(Tuple.Create("", 3683), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts/startup.js")
, 3683), false)
);

WriteLiteral("></script>\r\n");

WriteLiteral("    ");

            
            #line 86 "..\..\Views\Shared\_Layout.cshtml"
Write(RenderSection("scripts", required: false));

            
            #line default
            #line hidden
WriteLiteral("\r\n</body>\r\n</html>");

        }
    }
}
#pragma warning restore 1591
