#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 2 "..\..\Views\Manage\ManageLogins.cshtml"
    using Microsoft.Owin.Security;
    
    #line default
    #line hidden
    using MyBlog.Common.Extensions;
    using MyBlog.Common.Helpers;
    using MyBlog.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Manage/ManageLogins.cshtml")]
    public partial class _Views_Manage_ManageLogins_cshtml : System.Web.Mvc.WebViewPage<MyBlog.Web.Models.ManageLoginsViewModel>
    {
        public _Views_Manage_ManageLogins_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 3 "..\..\Views\Manage\ManageLogins.cshtml"
  
    ViewBag.Title = "Manage your external logins";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<h2>");

            
            #line 7 "..\..\Views\Manage\ManageLogins.cshtml"
Write(ViewBag.Title);

            
            #line default
            #line hidden
WriteLiteral(".</h2>\r\n\r\n<p");

WriteLiteral(" class=\"text-success\"");

WriteLiteral(">");

            
            #line 9 "..\..\Views\Manage\ManageLogins.cshtml"
                   Write(ViewBag.StatusMessage);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");

            
            #line 10 "..\..\Views\Manage\ManageLogins.cshtml"
 if (Model.CurrentLogins.Count > 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <h4>Registered Logins</h4>\r\n");

WriteLiteral("    <table");

WriteLiteral(" class=\"table\"");

WriteLiteral(">\r\n        <tbody>\r\n");

            
            #line 15 "..\..\Views\Manage\ManageLogins.cshtml"
            
            
            #line default
            #line hidden
            
            #line 15 "..\..\Views\Manage\ManageLogins.cshtml"
             foreach (var account in Model.CurrentLogins)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");

            
            #line 18 "..\..\Views\Manage\ManageLogins.cshtml"
                   Write(account.LoginProvider);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td>\r\n");

            
            #line 20 "..\..\Views\Manage\ManageLogins.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Manage\ManageLogins.cshtml"
                         if (ViewBag.ShowRemoveButton)
                        {
                            using (Html.BeginForm("RemoveLogin", "Manage"))
                            {
                                
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Manage\ManageLogins.cshtml"
                           Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Manage\ManageLogins.cshtml"
                                                        

            
            #line default
            #line hidden
WriteLiteral("                                <div>\r\n");

WriteLiteral("                                    ");

            
            #line 26 "..\..\Views\Manage\ManageLogins.cshtml"
                               Write(Html.Hidden("loginProvider", account.LoginProvider));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("                                    ");

            
            #line 27 "..\..\Views\Manage\ManageLogins.cshtml"
                               Write(Html.Hidden("providerKey", account.ProviderKey));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                    <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteLiteral(" value=\"Remove\"");

WriteAttribute("title", Tuple.Create(" title=\"", 1071), Tuple.Create("\"", 1137)
, Tuple.Create(Tuple.Create("", 1079), Tuple.Create("Remove", 1079), true)
, Tuple.Create(Tuple.Create(" ", 1085), Tuple.Create("this", 1086), true)
            
            #line 28 "..\..\Views\Manage\ManageLogins.cshtml"
                                  , Tuple.Create(Tuple.Create(" ", 1090), Tuple.Create<System.Object, System.Int32>(account.LoginProvider
            
            #line default
            #line hidden
, 1091), false)
, Tuple.Create(Tuple.Create(" ", 1113), Tuple.Create("login", 1114), true)
, Tuple.Create(Tuple.Create(" ", 1119), Tuple.Create("from", 1120), true)
, Tuple.Create(Tuple.Create(" ", 1124), Tuple.Create("your", 1125), true)
, Tuple.Create(Tuple.Create(" ", 1129), Tuple.Create("account", 1130), true)
);

WriteLiteral(" />\r\n                                </div>\r\n");

            
            #line 30 "..\..\Views\Manage\ManageLogins.cshtml"
                            }
                        }
                        else
                        {

            
            #line default
            #line hidden
WriteLiteral("                            ");

WriteLiteral(" &nbsp;\r\n");

            
            #line 35 "..\..\Views\Manage\ManageLogins.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </td>\r\n                </tr>\r\n");

            
            #line 38 "..\..\Views\Manage\ManageLogins.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n");

            
            #line 41 "..\..\Views\Manage\ManageLogins.cshtml"
}

            
            #line default
            #line hidden
            
            #line 42 "..\..\Views\Manage\ManageLogins.cshtml"
 if (Model.OtherLogins.Count > 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <h4>Add another service to log in.</h4>\r\n");

WriteLiteral("    <hr />\r\n");

            
            #line 46 "..\..\Views\Manage\ManageLogins.cshtml"
    using (Html.BeginForm("LinkLogin", "Manage"))
    {
        
            
            #line default
            #line hidden
            
            #line 48 "..\..\Views\Manage\ManageLogins.cshtml"
   Write(Html.AntiForgeryToken());

            
            #line default
            #line hidden
            
            #line 48 "..\..\Views\Manage\ManageLogins.cshtml"
                                

            
            #line default
            #line hidden
WriteLiteral("        <div");

WriteLiteral(" id=\"socialLoginList\"");

WriteLiteral(">\r\n        <p>\r\n");

            
            #line 51 "..\..\Views\Manage\ManageLogins.cshtml"
            
            
            #line default
            #line hidden
            
            #line 51 "..\..\Views\Manage\ManageLogins.cshtml"
             foreach (AuthenticationDescription p in Model.OtherLogins)
            {

            
            #line default
            #line hidden
WriteLiteral("                <button");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-default\"");

WriteAttribute("id", Tuple.Create(" id=\"", 1849), Tuple.Create("\"", 1875)
            
            #line 53 "..\..\Views\Manage\ManageLogins.cshtml"
, Tuple.Create(Tuple.Create("", 1854), Tuple.Create<System.Object, System.Int32>(p.AuthenticationType
            
            #line default
            #line hidden
, 1854), false)
);

WriteLiteral(" name=\"provider\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1892), Tuple.Create("\"", 1921)
            
            #line 53 "..\..\Views\Manage\ManageLogins.cshtml"
                                , Tuple.Create(Tuple.Create("", 1900), Tuple.Create<System.Object, System.Int32>(p.AuthenticationType
            
            #line default
            #line hidden
, 1900), false)
);

WriteAttribute("title", Tuple.Create(" title=\"", 1922), Tuple.Create("\"", 1966)
, Tuple.Create(Tuple.Create("", 1930), Tuple.Create("Log", 1930), true)
, Tuple.Create(Tuple.Create(" ", 1933), Tuple.Create("in", 1934), true)
, Tuple.Create(Tuple.Create(" ", 1936), Tuple.Create("using", 1937), true)
, Tuple.Create(Tuple.Create(" ", 1942), Tuple.Create("your", 1943), true)
            
            #line 53 "..\..\Views\Manage\ManageLogins.cshtml"
                                                                               , Tuple.Create(Tuple.Create(" ", 1947), Tuple.Create<System.Object, System.Int32>(p.Caption
            
            #line default
            #line hidden
, 1948), false)
, Tuple.Create(Tuple.Create(" ", 1958), Tuple.Create("account", 1959), true)
);

WriteLiteral(">");

            
            #line 53 "..\..\Views\Manage\ManageLogins.cshtml"
                                                                                                                                                                               Write(p.AuthenticationType);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n");

            
            #line 54 "..\..\Views\Manage\ManageLogins.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </p>\r\n        </div>\r\n");

            
            #line 57 "..\..\Views\Manage\ManageLogins.cshtml"
    }
}

            
            #line default
            #line hidden
WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
