#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using MyBlog.Common.Extensions;
    using MyBlog.Common.Helpers;
    using MyBlog.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Post/PostDetail.cshtml")]
    public partial class _Views_Post_PostDetail_cshtml : System.Web.Mvc.WebViewPage<MyBlog.Domain.PostEntity>
    {
        public _Views_Post_PostDetail_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 2 "..\..\Views\Post\PostDetail.cshtml"
  
    ViewBag.Title = Model.Title;

            
            #line default
            #line hidden
WriteLiteral("\r\n");

DefineSection("header", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 6 "..\..\Views\Post\PostDetail.cshtml"
Write(Html.GenerateMetaTag(
        keyword: Model.Tags.Aggregate(string.Empty, (current, tag) => current + (", " + tag.Name)).TrimStart(','),
        description: Model.Title,
        allowIndexPage: true,
        allowFollowLinks: true,
        author: "محسن اسماعیل پور",
        cacheControlType: HtmlExtensions.CacheControlType.Private));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 13 "..\..\Views\Post\PostDetail.cshtml"
Write(Styles.Render("~/content/prism.css"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n<div");

WriteLiteral(" class=\"col-lg-9 col-lg-offset-2 col-md-10 col-md-offset-1\"");

WriteLiteral(">\r\n    <h2>");

            
            #line 17 "..\..\Views\Post\PostDetail.cshtml"
   Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral("</h2>\r\n    <div");

WriteLiteral(" class=\"post-content\"");

WriteLiteral(">\r\n");

WriteLiteral("        ");

            
            #line 19 "..\..\Views\Post\PostDetail.cshtml"
   Write(Html.Raw(Model.Content));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n\r\n    <p");

WriteLiteral(" class=\"post-meta\"");

WriteLiteral(">\r\n        <a><i");

WriteLiteral(" class=\"glyphicon glyphicon-calendar\"");

WriteLiteral("></i></a>&nbsp;<span");

WriteLiteral(" class=\"date\"");

WriteLiteral(">");

            
            #line 23 "..\..\Views\Post\PostDetail.cshtml"
                                                                               Write(Model.CreateDate.ToJalaliDateTimeFullString().ToPersianDigits());

            
            #line default
            #line hidden
WriteLiteral("</span> <span");

WriteLiteral(" class=\"divider-vertical\"");

WriteLiteral("></span>\r\n        <a> <i");

WriteLiteral(" class=\"glyphicon glyphicon-tag\"");

WriteLiteral("></i></a>&nbsp;\r\n        <span>\r\n");

            
            #line 26 "..\..\Views\Post\PostDetail.cshtml"
            
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Post\PostDetail.cshtml"
             foreach (var tag in Model.Tags)
            {

            
            #line default
            #line hidden
WriteLiteral("                <a");

WriteAttribute("href", Tuple.Create(" href=\"", 1043), Tuple.Create("\"", 1108)
            
            #line 28 "..\..\Views\Post\PostDetail.cshtml"
, Tuple.Create(Tuple.Create("", 1050), Tuple.Create<System.Object, System.Int32>(Url.Action("PostsByTag", "Post", new { slug = tag.Slug })
            
            #line default
            #line hidden
, 1050), false)
);

WriteLiteral(">");

            
            #line 28 "..\..\Views\Post\PostDetail.cshtml"
                                                                                Write(tag.Name);

            
            #line default
            #line hidden
WriteLiteral("</a>");

WriteLiteral("&nbsp;");

WriteLiteral("\r\n");

            
            #line 29 "..\..\Views\Post\PostDetail.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </span>\r\n    </p>\r\n    <hr />\r\n\r\n    <div");

WriteLiteral(" id=\"disqus_thread\"");

WriteLiteral("></div>\r\n</div>\r\n\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n");

WriteLiteral("    ");

            
            #line 39 "..\..\Views\Post\PostDetail.cshtml"
Write(Scripts.Render("~/scripts/prism.js"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        $(function () {
            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
            var disqus_shortname = 'mohsenes'; // required: replace example with your forum shortname
            var disqus_identifier = '");

            
            #line 44 "..\..\Views\Post\PostDetail.cshtml"
                                Write(Model.Id);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n            var disqus_title = \'");

            
            #line 45 "..\..\Views\Post\PostDetail.cshtml"
                           Write(Model.Title);

            
            #line default
            #line hidden
WriteLiteral(@"';

            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function () {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        });
    </script>
    <noscript>Please enable JavaScript to view the <a");

WriteLiteral(" href=\"https://disqus.com/?ref_noscript\"");

WriteLiteral(">comments powered by Disqus.</a></noscript>\r\n");

});

        }
    }
}
#pragma warning restore 1591
